title: Northern Information
email: tyler@etters.co
description: Northern Information is the abstraction of polymath-artist Tyler Etters.
baseurl: /
url: https://nor.the-rn.info
image_path: /assets/images/
permalink: pretty
sort_by: year, month
order: reverse
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
feed:
  path: feed.xml
jekyll_compose:
    auto_open: true
include: ['_pages']