baseurl: /
url: https://nor.the-rn.info
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
include: ['_pages']
excerpt_separator: <!--x-->