title: Northern Information
description: Northern Information is the abstraction of polymath-artist Tyler Etters.
description_short: The abstraction of polymath-artist Tyler Etters.
twitter_site: "@tyleretters"
twitter_creator: "@tyleretters"
twitter_image_src: /TODO.png
og_image: /TODO.png