title: Northern Information, LLC
description: Northern Information, LLC is the abstraction of polymath-artist Tyler Etters.
description_short: The abstraction of polymath-artist Tyler Etters.
twitter_site: "@tyleretters"
twitter_creator: "@tyleretters"
twitter_image_src: /assets/images/eye.jpg
og_image: /assets/images/eye.jpg
github: https://github.com/tyleretters/nor.the-rn.info/blob/main